server:
  port: 8080
  servlet:
    context-path: /web

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"

app:
  locale:
    default: ja # ja, vi, en,...
  timezone:
    default: Asia/Ho_Chi_Minh # Asia/Tokyo, Asia/Ho_Chi_Minh,...

  slf4j-filter:
    request-header: 'X-Client-Id' # Can leave empty on production, set it on development and staging if you want to debug
    response-header: 'X-Client-Id'

  logging:
    enable-log-request: true
    enable-log-response: true
    log-response-time:
      enable: true
      exclude: >
        /example-path-1,
        /example-path-2,
        /custom-validation-message
      include: >
    debug: true
