server:
  port: 8081
  servlet:
    context-path: /webmvc

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: 12345678
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"

app:
  locale:
    default: ja # ja, vi, en,...
    language-parameter: lang
