server:
  port: 8080
  servlet:
    context-path: /web

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

jwt:
  key: vndevteam-kotlin-web-spring-boot-base-jvm
  jwt-token-expiration: 5
  refresh-token-expiration: 30

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"

app:
  locale:
    default: ja # ja, vi, en,...

  slf4j-filter:
    request-header: 'X-Client-Id' # Can leave empty on production, set it on development and staging if you want to debug
    response-header: 'X-Client-Id'

  logging:
    enable-log-request: true
    enable-log-response: true
    log-response-time:
      enable: true
      exclude: >
      include: >
    debug: true
